name: Maven Action Workflow DBL 
on:
  push:
    branches:
      - main
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Initialization
        run: |
          echo "Initialization"
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
          echo "${DBL_GITHUB_TOKEN}"
          echo "${MY_GITHUB_TOKEN}"
          echo "${GH_TOKEN}"
  codeql:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: CODEQL Running
        run: |
          echo "CODEQL Code Scan Running: Open 'Push on main' job output"
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: mvn -file pom.xml install -Denv.build.num=1234 -Denv.change.set.num=1234frtt
    - name: Build output statements
      run: |
        echo "Build with Maven completed successfully...."
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: mvn -file pom.xml install -Denv.build.num=1234 -Denv.change.set.num=1234frtt
    - name: Publish to GitHub Packages
      run: mvn deploy:deploy-file -Dfile=target/devops-api-0.0.10-SNAPSHOT.jar -DpomFile=./pom.xml -DrepositoryId=github -Durl=https://maven.pkg.github.com/dblucas-ops/my-services-devops -Dtoken=DBL_GITHUB_TOKEN
      env:
        GH_TOKEN: ${{ secrets.DBL_GITHUB_TOKEN }}
