name: Maven Action Workflow DBL 
on:
  push:
    branches:
      - main
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Initialization
        run: |
          echo "Initialization"
          echo "$(date +'%Y-%m-%d %H:%M:%S')"
          echo "${{ secrets.DBL_GITHUB_TOKEN }}"
  codeql:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: CODEQL Running
        run: |
          echo "CODEQL Code Scan Running: Open Push on main job output"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: mvn -file pom.xml install -Denv.build.num=1234 -Denv.change.set.num=1234frtt
    - name: Build output statements
      run: |
        echo "Build with Maven completed successfully...."
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Search for settings.xml
      run: | 
        mvn -X clean | grep "settings"
        cp -f settings.xml /usr/share/apache-maven-3.8.8/conf/settings.xml
        cp -f settings.xml /home/runner/.m2/settings.xml
    - name: Build with Maven
      run: mvn -file pom.xml install -Denv.build.num=1234 -Denv.change.set.num=1234frtt
    - name: Publish to GitHub Packages
      run: |
        echo "${{env.GITHUB_ACTOR}}"
        echo "${{env.GITHUB_TOKEN}}"
        mvn -s settings.xml deploy
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
